### ISSUE TITLE
3.2.8 - not starting at all

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nextcloud#19] opened 2022-06-22 06:53 UTC
Something seems to be wrong in the current version - here, it is not starting at all.
After a docker-compose up (-d), no messages appear at all.

When I enter the container and manually start all the startup scripts, it starts, but I don't get where the show stops.

When I change the Dockerfile to 
`FROM docker.io/tiredofit/nginx-php-fpm:alpine-3.15`
the container starts alright. So, some change/addition in the nginx container breaks the system at a point before the first debug printout.

What can I do to further narrow down the issue?

**Comment by joergmschulz** [comment] 2022-06-22 07:28
Maybe this one? https://github.com/just-containers/s6-overlay/commit/6b7a396f5ae43946ffe2d5859c04ae4552938d9a

**Comment by tiredofit** [comment] 2022-06-22 14:59
I got a report as well here: https://github.com/tiredofit/docker-freescout/issues/83 on another image.
I can't reproduce as I am running the images in a couple production environments (Fairly standard, docker-compose, Arch, 5.17 kernel, x86_64). 

What I'm going to do is rebuild all the images (tiredofit/alpine, tiredofit/nginx, tiredofit/nginx-php-fpm, and then each of these tagged releases) the process takes a few hours but I will be in touch when they are updated and we'll see what we come up with.

**Comment by tiredofit** [comment] 2022-06-22 19:53
Images are now rebuilt for 23 and 24. Odd how I can't recreate it on any of my machines. Whats your container orchestrator?

**Comment by joergmschulz** [comment] 2022-06-22 21:08
docker-compose.
The new images behave just the same. If you can't reproduce: Maybe one of your runtime environment settings helps. How could I debug this issue - I need some 'printfs' on container startup I assume. Hope I find some minutes to test tomorrow.

**Comment by joergmschulz** [comment] 2022-06-23 06:54
indeed: 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/6523646/175234721-eef09107-040a-4c8a-989b-0ca399b28811.png">

**Comment by joergmschulz** [comment] 2022-06-23 14:25
https://github.com/just-containers/s6-overlay/issues/456 seems to be resolved - could you re-trigger a build?

**Comment by joergmschulz** [comment] 2022-06-23 20:21
this issue has been resolved in the latest version (upstream fixes for S6). Thank you!

**Closed** 2022-06-23 20:21 UTC
Labels: bug
